A few TypeScript declaration updates
daily-co/daily-js pull request #131
Opened 2020-10-09 21:00 UTC by kompfner

2020-10-09 21:01 UTC, kompfner commented
@philmillman, discovered these while working on the corresponding RN update

2020-10-13 17:42 UTC, philmillman requested changes

2020-10-13 18:37 UTC, kompfner commented on index.d.ts
> +    backgroundColor?: string;
huh, looking at the code it does seem like these arguments are passed all the way to the gstreamer script. or do you mean that if we pass in anything other than the defaults (1920 x 1080, #0xff000000) it's untested and might yield unexpected results?

2020-10-13 18:44 UTC, philmillman commented on index.d.ts
> +    backgroundColor?: string;
IIRC the settings are fixed at 1080p @ 20fps, keyframe every 3s, 5mbit, @kwindla ??

2020-10-13 18:45 UTC, philmillman commented on index.d.ts
> +    backgroundColor?: string;
Or possibly only tested at those settings

2020-10-14 00:43 UTC, kwindla commented on index.d.ts
> +    backgroundColor?: string;
@philmillman is right that we've only done significant testing with the default width and height. (I have tested with the background color set to different values.)

My suggestion is that we remove `width`/`height` from the .ts definitions, but leave `backgroundColor`.

2020-10-14 00:44 UTC, kwindla approved these changes
lgtm other than the `width` and `height` arguments to `startLiveStreaming()`.

2020-10-14 13:31 UTC, kompfner commented
Merging with `width` and `height` removed

2020-10-14 13:32 UTC, merged